"""11-workspace-ownership-model

Revision ID: 2896211836fc
Revises: 7502f3f6c0b3
Create Date: 2026-09-19 13:49:33.120993

"""

import uuid
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2896211836fc"
down_revision: Union[str, Sequence[str], None] = "7502f3f6c0b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    workspace_id = uuid.uuid4()
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("forms", sa.Column("workspace_id", sa.UUID(), nullable=True))
    op.execute(
        sa.text("INSERT INTO workspaces (id, name) VALUES (:id, :name)").bindparams(
            id=workspace_id,
            name="Default Workspace",
        )
    )
    op.execute(
        sa.text(
            "UPDATE forms SET workspace_id = :workspace_id WHERE workspace_id IS NULL"
        ).bindparams(workspace_id=workspace_id)
    )
    op.alter_column("forms", "workspace_id", nullable=False)
    op.create_index("ix_forms_workspace_id", "forms", ["workspace_id"], unique=False)
    op.create_foreign_key(
        "forms_workspace_id_fkey", "forms", "workspaces", ["workspace_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("forms_workspace_id_fkey", "forms", type_="foreignkey")
    op.drop_index("ix_forms_workspace_id", table_name="forms")
    op.drop_column("forms", "workspace_id")
    op.drop_table("workspaces")
    # ### end Alembic commands ###
