"""queue-trigger

Revision ID: 7502f3f6c0b3
Revises: a9f1a893a862
Create Date: 2026-09-18 14:17:12.105376

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7502f3f6c0b3"
down_revision: Union[str, Sequence[str], None] = "a9f1a893a862"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deliveries",
        sa.Column(
            "queued_trigger",
            sa.Enum("AUTOMATIC", "RETRY", "MANUAL_REPLAY", name="deliverytrigger"),
            nullable=False,
            server_default="AUTOMATIC",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deliveries", "queued_trigger")
    # ### end Alembic commands ###

    op.execute("DROP TYPE IF EXISTS deliverytrigger CASCADE")
