"""Add db indexes

Revision ID: a9f1a893a862
Revises: 0bc438ed7411
Create Date: 2026-09-15 11:54:20.876921

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9f1a893a862"
down_revision: Union[str, Sequence[str], None] = "0bc438ed7411"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_deliveries_awaiting_retry_next_retry_at",
        "deliveries",
        ["next_retry_at"],
        unique=False,
        postgresql_where=sa.text("status = 'AWAITING_RETRY'"),
    )
    op.create_index(
        "ix_deliveries_destination_id", "deliveries", ["destination_id"], unique=False
    )
    op.create_index(
        "ix_delivery_attempts_delivery_id_created_at",
        "delivery_attempts",
        ["delivery_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_destinations_form_id", "destinations", ["form_id"], unique=False
    )
    op.create_index(
        "ix_submissions_form_id_created_at",
        "submissions",
        ["form_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_submissions_form_id_created_at", table_name="submissions")
    op.drop_index("ix_destinations_form_id", table_name="destinations")
    op.drop_index(
        "ix_delivery_attempts_delivery_id_created_at", table_name="delivery_attempts"
    )
    op.drop_index("ix_deliveries_destination_id", table_name="deliveries")
    op.drop_index(
        "ix_deliveries_awaiting_retry_next_retry_at",
        table_name="deliveries",
        postgresql_where=sa.text("status = 'AWAITING_RETRY'"),
    )
    # ### end Alembic commands ###
