class WorkspaceAccessDeniedError(Exception): ...


class InvalidCredentialsError(Exception): ...


class WorkspacePermissionDeniedError(Exception): ...


class UserAlreadyExistsError(Exception): ...


class WorkspaceNotFoundError(Exception): ...


class DeliveryNotFoundError(Exception): ...


class DeliveryNotReplayableError(Exception): ...


class InvalidSubmissionPayloadError(Exception): ...
